# Generated by Django 5.2.15 on 2026-06-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_file',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_thumb',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cover_file',
            field=models.CharField(blank=True, help_text='Clé stockage objet (WebP)', max_length=300),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cover_thumb',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo_file',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo_thumb',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
