# Generated by Django 5.2.15 on 2026-06-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_opening_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('tacos', 'Tacos'), ('kebab', 'Kebab'), ('sushi', 'Sushi'), ('burger', 'Burger'), ('healthy', 'Healthy'), ('asian', 'Asiatique'), ('medical', 'Médical'), ('dessert', 'Dessert'), ('drinks', 'Boissons'), ('supermarket', 'Supermarché'), ('shop', 'Magasins'), ('parapharmacy', 'Parapharmacie')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Numéro WhatsApp du restaurant (ex. +212539123456)', max_length=30),
        ),
    ]
