# Generated by Django 5.2.15 on 2026-08-02 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0008_alter_restaurant_cuisine_alter_restaurant_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("offer_type", models.CharField(choices=[("percentage", "Réduction %"), ("buy_get_free", "Acheté X, offert Y"), ("min_spend", "Montant minimum")], max_length=20)),
                ("title", models.CharField(help_text="Ex: -50% sur tout le menu", max_length=150)),
                ("description", models.TextField(blank=True)),
                ("discount_percent", models.PositiveIntegerField(blank=True, help_text="Pourcentage de réduction (1-100)", null=True)),
                ("buy_quantity", models.PositiveIntegerField(blank=True, help_text="Quantité à acheter (ex: 2)", null=True)),
                ("get_quantity", models.PositiveIntegerField(blank=True, help_text="Quantité offerte (ex: 1)", null=True)),
                ("free_item_name", models.CharField(blank=True, help_text="Nom de l'article offert (ex: Boisson 33cl)", max_length=200)),
                ("min_amount", models.DecimalField(blank=True, decimal_places=2, help_text="Montant minimum de la commande en MAD", max_digits=10, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("restaurant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="offers", to="restaurants.restaurant")),
            ],
            options={
                "verbose_name": "Offre restaurant",
                "verbose_name_plural": "Offres restaurants",
                "ordering": ["-created_at"],
            },
        ),
    ]
