# Generated by Django 5.2.15 on 2026-08-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0009_restaurantoffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="delivery_time",
            field=models.CharField(blank=True, default="30-45 min", max_length=40),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="rating",
            field=models.CharField(blank=True, default="4.8", max_length=10),
        ),
    ]
