# Generated by Django 5.2.15 on 2026-08-03 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_seed_mr_tacos'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='glovo_address_id',
            field=models.BigIntegerField(blank=True, help_text="ID de l'adresse Glovo du store.", null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='glovo_enabled',
            field=models.BooleanField(default=False, help_text="Menu synchronisé depuis l'API Glovo (toutes les 2 jours)."),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='glovo_slug',
            field=models.CharField(blank=True, help_text='Slug interne Glovo (ex: mr-tacos-tgr) pour la découverte.', max_length=120),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='glovo_store_id',
            field=models.BigIntegerField(blank=True, help_text='ID du store Glovo (découvert) — active la synchro du menu.', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='glovo_synced_at',
            field=models.DateTimeField(blank=True, help_text='Dernière synchronisation réussie du menu Glovo.', null=True),
        ),
        migrations.CreateModel(
            name='GlovoSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=120)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'En cours'), ('ok', 'Réussi'), ('error', 'Erreur'), ('up_to_date', 'Déjà à jour'), ('disabled', 'Désactivé')], default='running', max_length=20)),
                ('dry_run', models.BooleanField(default=False)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glovo_sync_logs', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'log synchro Glovo',
                'verbose_name_plural': 'logs synchro Glovo',
                'ordering': ['-started_at'],
            },
        ),
    ]
