# Generated by Django 5.2.15 on 2026-08-03 15:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_glovo_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('min_selected', models.PositiveSmallIntegerField(default=0)),
                ('max_selected', models.PositiveSmallIntegerField(default=1)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='restaurants.menuitem')),
            ],
            options={
                'verbose_name': "groupe d'options",
                'verbose_name_plural': "groupes d'options",
                'ordering': ['sort_order', 'id'],
                'unique_together': {('menu_item', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItemModifierOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('price_impact', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='restaurants.menuitemmodifiergroup')),
            ],
            options={
                'verbose_name': 'option',
                'verbose_name_plural': 'options',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('group', 'name')},
            },
        ),
    ]
