# Generated by Django 5.2.15 on 2026-06-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderpushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_delivery_at',
            field=models.DateTimeField(blank=True, help_text='Plage de livraison choisie par le client (début de la tranche de 30 min)', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_instructions',
            field=models.TextField(blank=True, help_text='Remarques client pour le restaurant (ex. sans tomate)'),
        ),
    ]
