# Generated by Django 5.x — allonge public_id commandes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_orderline_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="public_id",
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
    ]
