# Generated by Django 5.2.15 on 2026-07-31 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_ar', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('address_ar', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.CharField(db_index=True, default='Tanger', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('website', models.URLField(blank=True, default='')),
                ('source', models.CharField(default='infopoint', max_length=50)),
                ('source_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pharmacie',
                'verbose_name_plural': 'Pharmacies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('guard_type', models.CharField(choices=[('day', 'Jour'), ('night', 'Nuit'), ('24h', '24h')], default='24h', max_length=10)),
                ('hours_label', models.CharField(blank=True, default='', max_length=255)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('start_time_2', models.TimeField(blank=True, null=True)),
                ('end_time_2', models.TimeField(blank=True, null=True)),
                ('source', models.CharField(default='infopoint', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='pharmacy.pharmacy')),
            ],
            options={
                'verbose_name': 'Garde',
                'verbose_name_plural': 'Gardes',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('pharmacy', 'date'), name='unique_pharmacy_duty_per_day')],
            },
        ),
    ]
