# Generated by Django 5.2.15 on 2026-07-30 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('heading', models.FloatField(default=0.0, verbose_name='Cap (Degrés 0-360)')),
                ('speed', models.FloatField(default=0.0, verbose_name='Vitesse (km/h)')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='Livreur')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_locations', to='orders.order', verbose_name='Commande active')),
            ],
            options={
                'verbose_name': 'Position Livreur',
                'verbose_name_plural': 'Positions Livreurs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['courier', '-timestamp'], name='locations_c_courier_ae4b05_idx'), models.Index(fields=['order', '-timestamp'], name='locations_c_order_i_714927_idx')],
            },
        ),
    ]
