# Generated by Django 5.2.15 on 2026-06-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUnsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCampaignState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation_index', models.PositiveIntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_campaign_key', models.CharField(blank=True, max_length=40)),
                ('last_restaurant_slug', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'État campagne promo',
            },
        ),
        migrations.CreateModel(
            name='PromoEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('campaign_key', models.CharField(db_index=True, max_length=40)),
                ('restaurant_slug', models.CharField(blank=True, max_length=120)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['campaign_key', 'sent_at'], name='marketing_p_campaig_ce809b_idx')],
                'unique_together': {('email', 'campaign_key')},
            },
        ),
    ]
