# Generated by Django 5.2.15 on 2026-06-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('discount', models.PositiveIntegerField(help_text='Remise en % (1-100)')),
                ('section', models.CharField(choices=[('all', 'Toutes les sections'), ('restaurant', 'Restaurants'), ('patisserie', 'Pâtisseries'), ('pharmacy', 'Pharmacies'), ('parapharmacy', 'Parapharmacies'), ('supermarket', 'Supermarchés'), ('shop', 'Magasins')], default='all', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Code promo',
                'verbose_name_plural': 'Codes promo',
                'ordering': ['-created_at'],
            },
        ),
    ]
