# Generated by Django 5.1.15 on 2026-06-09 21:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beneficiary_type', models.CharField(max_length=20)),
                ('beneficiary_id', models.CharField(max_length=64)),
                ('total_mad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_mad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cod', 'Espèces à la livraison'), ('card', 'Carte (futur)')], default='cod', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('authorized', 'Autorisé'), ('captured', 'Encaissé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('order_total', 'Total commande'), ('service_fee', 'Frais de service'), ('platform_profit', 'Profit plateforme'), ('restaurant_payout', 'Versement restaurant'), ('courier_payout', 'Rémunération livreur'), ('refund', 'Remboursement')], max_length=30)),
                ('amount_mad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after_mad', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payments.payment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['entry_type', 'created_at'], name='payments_le_entry_t_f71668_idx'),
        ),
    ]
